### ISSUE TITLE
Error using old Git versions

### ISSUE THREAD

**Issue by elliottslaughter** [python-versioneer/python-versioneer#187]
Versioneer appears to make some assumptions about the Git version being used. In particular, the version 1.7.1 included in CentOS 6 causes errors like the following. Ideally, this would be fixed so that I don't have to give my users special instructions on how to update their Git. However, at a minimum, versioneer should detect the error so that I get a `0+unknown` version instead of a hard error. Right now I can't even install the software on such machines.

This is using versioneer 0.18 from conda-forge.

Repro steps at bottom of post.

```
Begin: setup.py build_ext --xtcdata=/lcls2/install -f --inplace
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    version=versioneer.get_version(),
  File "/lcls2/psana/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
  File "/lcls2/psana/versioneer.py", line 1453, in get_versions
    pieces = from_vcs_f(cfg.tag_prefix, root, verbose)
  File "/lcls2/psana/versioneer.py", line 1110, in git_pieces_from_vcs
    pieces["distance"] = int(count_out)  # total number of commits
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Reproduction steps:

```
docker run -ti slaclcls/travis:centos6-py3.6-versioneer-bug187
```

From inside this container, run:

```
source activate myrel
git clone https://github.com/slac-lcls/lcls2.git
cd lcls2
./build_travis.sh -p install
```

**Comment by FulgurIgor** [comment]
I made the following patch:
```diff

-        pieces["distance"] = int(count_out)  # total number of commits
+        pieces["distance"] = 0
+        if count_out != None:
+          pieces["distance"] = int(count_out)  # total number of commits
```

Then, all is working (I'm not really interesting about distance between commits, but it works)
