### ISSUE TITLE
Conflict with pip-tools

### ISSUE THREAD

**Issue by njiles** [python-versioneer/python-versioneer#231]
It appears that versioneer and [pip-tools](https://github.com/jazzband/pip-tools) don't work nicely together: following the instructions from [INSTALL.md](https://github.com/python-versioneer/python-versioneer/blob/master/INSTALL.md) and then running `pip-compile` causes
```bash
$ pip-compile
Traceback (most recent call last):
  File "/Users/njiles/anaconda3/envs/versioneer-piptools/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/njiles/anaconda3/envs/versioneer-piptools/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/njiles/anaconda3/envs/versioneer-piptools/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/njiles/anaconda3/envs/versioneer-piptools/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/njiles/anaconda3/envs/versioneer-piptools/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/njiles/anaconda3/envs/versioneer-piptools/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/njiles/anaconda3/envs/versioneer-piptools/lib/python3.8/site-packages/piptools/scripts/compile.py", line 393, in cli
    dist = run_setup(src_file)
  File "/Users/njiles/anaconda3/envs/versioneer-piptools/lib/python3.8/distutils/core.py", line 215, in run_setup
    exec(f.read(), g)
  File "<string>", line 9, in <module>
AttributeError: module 'versioneer' has no attribute 'get_version'
```

By adding some `print(sys.path)` and `print(dir(versioneer))` calls in setup.py, it looks like the `import versioneer` statement in setup.py imports the _package_ "versioneer" when called via `pip-compile`, not the _local file_ versioneer.py. Is there any way round this? Thanks!

**Comment by effigies** [comment]
You may want to check out https://github.com/python-versioneer/versioneer-518, which is supposed to work without vendoring.

After the next release, we'll be seeing about merging these two lines.

**Comment by njiles** [comment]
Thanks for the quick response - I have actually had a very similar issue using pip-tools without versioneer, so I have opened [an issue](https://github.com/jazzband/pip-tools/issues/1221) there. Happy for this to be closed, as it seems the issue is not to do with versioneer?

Regardless, I tried versioneer-518: `pip install versioneer-518` worked, but (following the versioneer installation instructions, since versioneer-518 doesn't appear to have any documentation), `versioneer install` gives a simple `versioneer: command not found` response. Instead, I copied versioneer.py from the versioneer-518 package to the root directory of my project and ran `python versioneer.py setup` - I hope this is correct? Unfortunately, this had the same error as in the original post (perhaps unsurprisingly, if it is indeed to do with pip-tools rather than versioneer).

Thanks again for the assistance!

**Comment by effigies** [comment]
There is an example repo that might help you find out if you're doing something wrong: https://github.com/python-versioneer/example-518

versioneer-518 is @bucknerns's effort, and I haven't looked at it closely. Possibly he can help?

**Comment by bucknerns** [comment]
The example repo is how you would set it up. The key parts are below

pyproject.toml
`
[build-system]
requires = ["setuptools", "versioneer-518"]
`

setup.py
```
# works without vendoring
import versioneer
...

setup(
    name="somename",
    version=version=versioneer.get_version(),
...
```

**Comment by effigies** [comment]
@njiles Does that answer your questions?

**Comment by njiles** [comment]
That's really helpful, thank you both!
