### ISSUE TITLE
Possible to `pip install .`?

### ISSUE THREAD

**Issue by ifiddes** [python-versioneer/python-versioneer#249]
I see the changes in https://github.com/python-versioneer/python-versioneer/commit/7776ee06b669b85c52a1fd0f6ad9c5a6a79c3904

which imply that it is still not possible to get a version from git when running `pip install .`. Is this true? Is there a workaround / known solution to this issue? I guess the core of the issue is that `pip` doesn't copy over the `.git` folder to the temporary directory, and so maybe this is simply impossible?

**Comment by effigies** [comment]
In general, I expect pip install to work. Do you have a project where it doesn't?

**Comment by yarikoptic** [comment]
<details>
<summary>I just did on versioneer itself and it seems to be fine</summary> 

```shell
$> py=3; d=venvs/dev$py; virtualenv --python=python$py --system-site-packages $d && source $d/bin/activate && pip3 install  . && versioneer --version 
created virtual environment CPython3.9.1.final.0-64 in 217ms
  creator CPython3Posix(dest=/home/yoh/proj/misc/python-versioneer/venvs/dev3, clear=False, no_vcs_ignore=False, global=True)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/yoh/.local/share/virtualenv)
    added seed packages: pip==20.1.1, pkg_resources==0.0.0, setuptools==44.0.0, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Processing /home/yoh/proj/misc/python-versioneer
Building wheels for collected packages: versioneer
  Building wheel for versioneer (setup.py) ... done
  Created wheel for versioneer: filename=versioneer-0.20.dev0-py3-none-any.whl size=38815 sha256=49a233a25b647436bb8dcd291b204f56af2e9d8af3559561970cb2d027265957
  Stored in directory: /home/yoh/.cache/pip/wheels/31/07/b1/d4006dcd5d1f54320cf8412c61458e934d69df7bdf6e5496cc
Successfully built versioneer
Installing collected packages: versioneer
Successfully installed versioneer-0.20.dev0
pip3 install .  5.22s user 0.73s system 99% cpu 5.982 total
versioneer (installer) 0.20.dev0
```
</details>


It doesn't work though for `-e .`!:

```shell
(git)lena:~/proj/misc/python-versioneer[master]git
$> py=3; d=venvs/dev$py; virtualenv --python=python$py --system-site-packages $d && source $d/bin/activate && pip3 install -e . && versioneer --version
created virtual environment CPython3.9.1.final.0-64 in 213ms
  creator CPython3Posix(dest=/home/yoh/proj/misc/python-versioneer/venvs/dev3, clear=False, no_vcs_ignore=False, global=True)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/yoh/.local/share/virtualenv)
    added seed packages: pip==20.1.1, pkg_resources==0.0.0, setuptools==44.0.0, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Obtaining file:///home/yoh/proj/misc/python-versioneer
Installing collected packages: versioneer
  Running setup.py develop for versioneer
Successfully installed versioneer
pip3 install -e .  6.32s user 0.87s system 99% cpu 7.188 total
Traceback (most recent call last):
  File "/home/yoh/proj/misc/python-versioneer/venvs/dev3/bin/versioneer", line 11, in <module>
    load_entry_point('versioneer', 'console_scripts', 'versioneer')()
  File "/home/yoh/proj/misc/python-versioneer/venvs/dev3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/yoh/proj/misc/python-versioneer/venvs/dev3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/yoh/proj/misc/python-versioneer/venvs/dev3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/yoh/proj/misc/python-versioneer/venvs/dev3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'versioneer'
```

may be that is what was your case @ifiddes ?

**Comment by Rasmnev** [comment]
I'm having this problem with both `pip install .` and `pip install -e .` 


```
Traceback (most recent call last):
    File "/home/ricardo/anaconda3/envs/forecast-off/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/ricardo/anaconda3/envs/forecast-off/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ricardo/anaconda3/envs/forecast-off/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-oqexy4pi/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-oqexy4pi/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-oqexy4pi/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 2, in <module>
      import versioneer
  ModuleNotFoundError: No module named 'versioneer'
  ----------------------------------------
WARNING: Discarding file:///home/Forecast-Off/new_repo/forecast-off-trade. Command errored out with exit status 1: /home/ricardo/anaconda3/envs/forecast-off/bin/python /home/ricardo/anaconda3/envs/forecast-off/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp0q02sf1v Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/ricardo/anaconda3/envs/forecast-off/bin/python /home/ricardo/anaconda3/envs/forecast-off/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp0q02sf1v Check the logs for full command output.
```

**Comment by Rasmnev** [comment]
> I hope this helps. I found this [snippet](https://github.com/judy2k/git-workout/blob/19a529935855bb6109ecc64525ec5635cafa592d/setup.py#L5) for setup.py in a repo by developer advocate @judy2k which solved the problem for me:
> 
> ```python
> import sys
> 
> # This appears to be necessary so that versioneer works:
> sys.path.insert(0, ".")  # noqa
> import versioneer
> ```

This solved it for me. Thanks

**Comment by effigies** [comment]
It seems a solution has been found, although I don't know why it's needed. No projects that I use have needed it...

**Comment by has2k1** [comment]
Here is the a failure case.  Create `pyproject.toml` with the following contents.

```toml
[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"
```

The culprit is  `build-backend = "setuptools.build_meta"` which triggers a build that is compliant with PEP 517 and PEP 518.
This is issue #193 all over again. The long term solution is to make it possible to use versioneer without vendoring it.

**Comment by effigies** [comment]
Ah, thanks.

**Comment by yarikoptic** [comment]
I would say that no solution was really found -- rather a workaround. Without proper solution poor yarik can spend a quality morning trying to figure out wtf versioneer does not work until he finds this issue!

**Comment by effigies** [comment]
@yarikoptic Care to review https://github.com/python-versioneer/python-versioneer/pull/294, then?

**Comment by effigies** [comment]
This should be fixed.

For vendored builds, using `build-backend = "setuptools.build_meta:__legacy__"` should work, or adding `sys.path.append(".")` in your `setup.py`. For non-vendored builds, adding `versioneer >= 0.24` to your `requires` list should work.
