### ISSUE TITLE
setup.py build_ext: TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

### ISSUE THREAD

**Issue by mgorny** [python-versioneer/python-versioneer#346]
```pytb
$ python setup.py build_ext
running build_ext
Traceback (most recent call last):
  File "/tmp/python-versioneer/setup.py", line 143, in <module>
    setup(
  File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "<string>", line 1903, in run
  File "<frozen posixpath>", line 90, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

git bisect points to the following commit:
```
commit d0861cf0a0a710f0b1947a10c6beaf6fd3257e64
Author: Chris Markiewicz <effigies@gmail.com>
Date:   Wed Oct 19 07:45:08 2022 -0400

    MNT: Move versioneer config to pyproject.toml

 pyproject.toml | 7 ++++++-
 setup.cfg      | 7 -------
 2 files changed, 6 insertions(+), 8 deletions(-)
 delete mode 100644 setup.cfg
```

**Comment by mgorny** [comment]
Ok, apparently this the problematic line from `cmd_build_ext.run()`:

```
            target_versionfile = os.path.join(self.build_lib,
                                              cfg.versionfile_build)
```

with `cfg.versionfile_build` being `None`.

**Comment by mgorny** [comment]
I'm guessing this is because `setup.cfg` had:

    versionfile_build =

while the key is entirely missing from `pyproject.toml`.

I see that `cmd_build_py` checks for it being "true" while `cmd_build_ext` does not. I'll submit a PR to fix that.
