### ISSUE TITLE
Support for the Meson-python build backend

### ISSUE THREAD

**Issue by MarkWieczorek** [python-versioneer/python-versioneer#387]
Does anyone know if it is possible to use the [Meson-python](https://github.com/mesonbuild/meson-python)  /  [Meson build system](https://github.com/mesonbuild/meson) with versioneer? If no, then this is a feature request!

In the `pyproject.toml`, the meson-python backend is chosen by setting

```
[build-system]
build-backend = 'mesonpy'
````
As far as I can tell, you can't use versioneer as it requires the `setuptools.build_meta` backend.

**Comment by effigies** [comment]
Versioneer was pretty specifically designed around setuptools, and there's been no serious attempt that I've seen to generalize it. Of course, anybody's welcome to hack on it and submit a PR...

**Comment by MarkWieczorek** [comment]
I kind of got versionneer to work with Meson (as shown in this [PR](https://github.com/SHTOOLS/SHTOOLS/pull/439) for a different project), but I think that a few changes could perhaps be made to make this work better.

First, in the `pyproject.toml` file, I added a "[tool.versioneer]" section. Then, when installing versioneer in no-vendor mode you get the following output

```
$ versioneer install --no-vendor
 creating pyshtools/_version.py
 pyshtools/__init__.py unmodified
Traceback (most recent call last):
  File "/Users/lunokhod/miniconda3/envs/py312/bin/versioneer", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/lunokhod/miniconda3/envs/py312/lib/python3.12/site-packages/versioneer.py", line 2001, in main
    setup_command()
  File "<string>", line 2270, in setup_command
  File "<string>", line 2235, in scan_setup_py
FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
```
It successfully creates a `_version.py` file, and the error seems to be related to the fact that we are using `build-backend = 'mesonpy'` instead of `setuptools.build_meta`.

In the main meson.build file, we defined the version as follows
```
project('shtools', 'c', 'fortran',
  version: run_command(find_program('python3'), '-c', 'import os; os.chdir("pyshtools"); import _version; print(_version.get_versions()["version"])').stdout().strip(),
  license: 'BSD-3-Clause',
  meson_version: '>=1.1.0',
  default_options: [
    'buildtype=release',
  ])
```
In `pyproject.toml`, we added

```
[project]
name = 'pyshtools'
dynamic = ['version']
````

And in the `__init__.py` file, we removed 
```
from . import _version
__version__ = _version.get_versions()['version']
```
and instead used
```
try:
    __version__ = version('pyshtools')
except PackageNotFoundError:
    # package is not installed
    pass
```
Even though the project now builds, when run from a source tarball, versioneer sets the version to the uninformative '0+unknown', which is better than failing.

If you run 
```
python -c 'import os; os.chdir("pyshtools"); import _version; print(_version.get_versions())'
```
you get
```
{'version': '0+unknown', 'full-revisionid': '9ec26db51f2f7a836b4c346e7f16328884a870f9', 'dirty': False, 'error': 'no suitable tags', 'date': None}
```
What is surprising to me is that the date is set to None, but when you inspect the `_version.py` file you see
```
    git_refnames = " (new_versioneer)"
    git_full = "9ec26db51f2f7a836b4c346e7f16328884a870f9"
    git_date = "2024-01-23 12:54:16 +0100"
    keywords = {"refnames": git_refnames, "full": git_full, "date": git_date}
```

I was also somewhat surprised that versionneer didn't deduce the version from the directory name, though I haven't dug too deep in the `_version.py` to see why not. Ideally, I would really like versioneer to produce something like `v4.11.10.devN` when run in a non-git-versioned folder, but maybe that isn't possible.

**Comment by effigies** [comment]
The error is just that there is no option not to look at `setup.py`:

https://github.com/python-versioneer/python-versioneer/blob/bdf701a688a410659a42c49cab6bd901389743d6/src/setupfunc.py#L115-L162

If you want to generalize this to another backend, maybe the approach would be to detect the backend from `pyproject.toml`, defaulting to `setuptools`, and then have a scan function per-backend. A fallback scan function could just report the backend and alert the user that we can't assure them they've set things up correctly.

Instead of the `chdir`, etc. You could try using [runpy](https://docs.python.org/3/library/runpy.html).

If you try from a `git archive` tarball, you should be able to see something better than `0+unknown`. How are you making your tarball?

**Comment by MarkWieczorek** [comment]
When I use `git archive`, `meson dist`, and downloading the source from github, the version is always `0+unknown`. 

Here is what gets rewritten in `_version.py` when using git archive:
```
def get_keywords() -> Dict[str, str]:
    """Get the keywords needed to look up the version information."""
    # these strings will be replaced by git during git-archive.
    # setup.py/versioneer.py will grep for the variable names, so they must
    # each be defined on a line of their own. _version.py will just call
    # get_keywords().
    git_refnames = " (HEAD -> new_versioneer, origin/new_versioneer)"
    git_full = "65ca9c0bc36940fe0ca9b2e577ef0b043ddcb25a"
    git_date = "2024-01-23 13:27:53 +0100"
    keywords = {"refnames": git_refnames, "full": git_full, "date": git_date}
    return keywords
```
and here is the `get_versions()` output:
```
{'version': '0+unknown', 'full-revisionid': '65ca9c0bc36940fe0ca9b2e577ef0b043ddcb25a', 'dirty': False, 'error': 'no suitable tags', 'date': None}
```

I note that the date is getting set correctly.

**Comment by JBorrow** [comment]
We currently have a halfway house; I've modified `_version.py` to have at the bottom a case to print out the versioneer-provided version by default when ran. Then in our meson.build, we have:

```
project(
    'pixell',
    ['c', 'fortran', 'cython'],
    version: run_command(
        [
            # Note that _version.py doesn't actually 'dynamically' set the
            # version number. We call it at build time and set it as a meson
            # property.
            'python',
            'pixell/_version.py'
        ],
        check: true,
    ).stdout().strip()
)
```

which freezes the version at _build time_, but it is still generated by versioneer. Then in `pyproject.toml` we write `dynamic = ['version']`.

This may be helpful but I can see it's not an officially supported use-case.
