### ISSUE TITLE
Tests failing with pip 24.0

### ISSUE THREAD

**Issue by sudhackar** [python-versioneer/python-versioneer#393]
```console
$ python --version
Python 3.11.9
$ pip --version
pip 24.0 from /home/sudhackar/.pyenv/versions/3.11.9/envs/venv-soss/lib/python3.11/site-packages/pip (python 3.11)
$ tox p -e py311-linux
.pkg: recreate env because python changed version_info=[3, 12, 3, 'final', 0]->[3, 11, 9, 'final', 0] | executable='/usr/bin/python3.12'->'/home/sudhackar/.pyenv/versions/3.11.9/bin/python3.11'
...
======================================================================
FAIL: test_pip_install (__main__.SetuptoolsWheel.test_pip_install)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/python-versioneer-upstream/test/git/test_invocations.py", line 465, in test_pip_install
    self.run_in_venv(venv, venv,
  File "/dev/shm/python-versioneer-upstream/test/git/test_invocations.py", line 85, in run_in_venv
    return self.command(*bin_args, *args, workdir=workdir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/shm/python-versioneer-upstream/test/git/common.py", line 16, in command
    self.fail("problem running command %s" % cmd)
AssertionError: problem running command /tmp/tmp5aim3n9h/venvs/setuptools-wheel-pip-install/bin/python

----------------------------------------------------------------------
Ran 28 tests in 250.710s

FAILED (failures=15)
  py311-linux: FAIL code 1 (316.33=setup[4.39]+cmd[0.15,0.07,0.33,0.05,60.55,250.80] seconds)
  evaluation failed :( (316.36 seconds)
```

pinning pip version to something like 23.2.1 will make the tests pass

```diff
diff --git a/test/git/test_invocations.py b/test/git/test_invocations.py
index 1f61ffb..e7e6b5a 100644
--- a/test/git/test_invocations.py
+++ b/test/git/test_invocations.py
@@ -58,6 +58,8 @@ class _Invocations(common.Common):
             self.run_in_venv(venv_dir, venv_dir,
                              'pip', 'install', '-U',
                              'pip', 'wheel', 'packaging')
+            self.run_in_venv(venv_dir, venv_dir, 'pip', 'install',
+                             'pip==23.2.1', '--upgrade')
         if sys.version_info.major == 3 and sys.version_info.minor >= 12:
             # Py 3.12 no longer default-installs setuptools in environments
             # See PEP-632
```

will pass

```
$ tox p -e py311-linux
  py311-linux: OK (492.07=setup[2.03]+cmd[0.14,0.06,0.13,0.04,60.69,428.31,0.13,0.06,0.05,0.07,0.24,0.11] seconds)
  congratulations :) (492.10 seconds)
```

**Comment by sudhackar** [comment]
Based on https://github.com/pypa/pip/issues/12933#issuecomment-2306623165 I'll raise a PR to move to tar.gz as standard

**Comment by Callek** [comment]
Thank you for the report and fix, I expect to review within the week (might be today, but not sure yet)

Just wanted to let you know that I saw this!
